inherit_from:
  private-rubocop-config: config/rubocop.yml
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Rails:
  Enabled: true
